### ISSUE TITLE
WooCommerce Store Archive Conflicts with Popups

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/BetterOptin#1]
When a popup is set on the WooCommerce "archive" page nothing loads. The reason is that the "archive" page is a regular page (created under the _Page_ menu in the admin), but WooCommerce somehow transforms it into an archive when displaying the page. The `$post` var is probably not defined as it should be on a normal page, meaning we need to find a way to get the page ID.

**Comment by SiamKreative** [comment]
This works as of March 2016 with version 2.0.1 & WC version 2.5.4.
