### ISSUE TITLE
Fallback for MailChimp / Aweber / MailPoet

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#11]
Currently, if for some reason the subscription fails, the user won't notice. Therefore, leads can be lost.

How about saving the email address in a text file in a protected directory (htaccess or else)? That way, if the subscription to a third part service fails, we can still "recover" these precious emails.

**Comment by julien731** [comment]
Proposed format for a fallback option is CSV.

**Comment by julien731** [comment]
See dd28135a9572e8af888fcd8ff1bf7101e701c7ed
