### ISSUE TITLE
Compatibility issue with MailChimp for WordPress

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/BetterOptin#12]
It seems that when [MailChimp for WordPress](https://wordpress.org/plugins/mailchimp-for-wp/) is installed alongside BetterOptin the submissions end up on a 503 error message and aren't saved into the MailChimp list.

**Comment by dannyvankooten** [comment]
Hi @julien731, Danny here, the author of MailChimp for WordPress. 

Let me know if there's anything I can help with, will look into this myself later this week.

PS. Bryce says hi! He recently told me about the work you've been doing on AwesomeSupport. Nice!

**Comment by julien731** [comment]
Hi @dannyvankooten very nice to have you here! I haven't had time to investigate yet but I'll work on this next week. If I need your help I'll definitely bug you ;)

**Comment by julien731** [comment]
I ran some quick tests and so far everything is working with BetterOptin 1.2.4 and MailCHimp for WordPress 2.2.3. I am able to submit e-mails from both plugins on the same page with no problem.
