### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by pagejumped** [ThemeAvenue/BetterOptin#17]
I've installed BetterOptin with Mailpoet integration but I'm having trouble with the popup. When I click on the text field or its accompanying image, it automatically closes the popup. Is this the behavior? 

Is it also possible to configure that they receive an email after they register their email address?

I tried to enter an email address but it wasn't captured in Wordpress. 

Please help. Thanks!

**Comment by SiamKreative** [comment]
We're in the process of refactoring the plugin. All of the above will be solved in the next version, which you'll be granted for free.
