### ISSUE TITLE
Use Select2 to select the "Return URL"

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#23]
Instead of just a text input, we should have a select2 dropdown, that list the pages / posts / custom post type / archives.

Exactly how it's done in Awesome Support (select with [optgroup](http://www.w3schools.com/tags/tag_optgroup.asp))...

**Comment by julien731** [comment]
What if the user wants a return URL that's not an internal page / post?

**Comment by SiamKreative** [comment]
Two options:
- Add somewhere "Pick from pages/post"
- Or add to select an option "Custom URL"

**Comment by SiamKreative** [comment]
```php
<?php
<p><?php printf( wp_kses( __( 'You can use the post ID, page ID or custom URL. <a href="%s">How To Find The Post ID In WordPress</a>.', 'betteroptin' ), array(  'a' => array( 'href' => array() ) ) ), esc_url( 'https://pagely.com/blog/2015/04/find-post-id-wordpress/' ) ); ?></p>

<p><?php printf( __( 'The return URL is optional. If not specified, the URL set in the general settings will be used (currently %s)', 'betteroptin' ), "<code>$returl</code>" ); ?></p>
```
