### ISSUE TITLE
Ability to send an email to a new lead

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#24]
* General Setting + Setting per popup: "Email sent to new leads" (tinyMCE editor, pre-populated with default message)
* Available email tags: `email`, `full_name` (depends on selected popup template), plus all the WordPress info from [get_bloginfo](https://codex.wordpress.org/Function_Reference/get_bloginfo)
* Recommend the use of Mandrill, MailGun for better email delivery. If possible, allow one-click install of one of these transactional email plugins.
* Style: see how EDD does it. https://github.com/easydigitaldownloads/Easy-Digital-Downloads/tree/1221a46e48dbb3e6c97b62418115d76c3084386e/templates/emails

**Comment by julien731** [comment]
My concern is that we'll start getting a lot of support requests related to e-mail delivery, which is not the job of this plugin. I'm not sure this is worth it in terms of support, especially now that all the providers will be built in the plugin.
