### ISSUE TITLE
Dashboard > Add two more columns

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#30]
I don't think we need to display stuff related to the popup UI (Close on Overlay, Close on «ESC», Overlay Color, etc), but it could be useful to display the following:

* Template: Which template did they use?
* Return URL: Is there a specific return URL set?

**Comment by julien731** [comment]
Which dashboard is that?

**Comment by SiamKreative** [comment]
The main popup list "All popups" (`/wp-admin/edit.php?post_type=wpbo-popup`). Users should still be able to use the Screen Options to hide those columns, but by default they should be enabled.
