### ISSUE TITLE
Get Fonts Locally

### ISSUE THREAD

**Issue by julien731** [ThemeAvenue/BetterOptin#32]
Using a third-party to retrieve the fonts list is not reliable ( see #19 ). We should switch to a local list that we would maintain manually with plugin updates.

**Comment by SiamKreative** [comment]
Can retrieve the JSON used here: https://www.kimonolabs.com/api/8qckyf28?apikey=34f710899fb2424aeb213c881ff10109&authorization=LFeEpGUJGpDu9Ak5CyFblPPQcT12BBRh

**Comment by SiamKreative** [comment]
This is critical and needs to be fixed asap @julien731. This is still broken as of version 2.0.1.

Furthermore, KimonoLabs has now closed and we don't even have a local copy...

> Kimono shut down on February 29th, 2016 and the cloud service has been discontinued. Your APIs can still be accessed via Kimono for Desktop. Download the application and import your APIs before March 31, 2016. If you need you to reset your password, you may do so from here. See the FAQ for more details.

**Comment by SiamKreative** [comment]
Could perhaps use this for now:

```json
{
	"lastUpdated": 1457672759,
	"count": 13,
	"source": "http://www.w3schools.com/cssref/css_websafe_fonts.asp",
	"fonts": {
		"serif": [
			"Georgia, serif",
			"'Palatino Linotype', 'Book Antiqua', Palatino, serif",
			"'Times New Roman', Times, serif"
		],
		"sansserif": [
			"Arial, Helvetica, sans-serif",
			"'Arial Black', Gadget, sans-serif",
			"'Comic Sans MS', cursive, sans-serif",
			"Impact, Charcoal, sans-serif",
			"'Lucida Sans Unicode', 'Lucida Grande', sans-serif",
			"Tahoma, Geneva, sans-serif",
			"'Trebuchet MS', Helvetica, sans-serif",
			"Verdana, Geneva, sans-serif"
		],
		"monospace": [
			"'Courier New', Courier, monospace",
			"'Lucida Console', Monaco, monospace"
		]
	}
}
```
