### ISSUE TITLE
Development stopped? "Exit Intent" patented?

### ISSUE THREAD

**Issue by FiddlerStudios** [ThemeAvenue/BetterOptin#33]
Sorry to post this here, as it's not technically an issue with the functionality of the plugin itself, but the contact form on betteropt.in does not appear to be working, and the SSL is expired.

I'm wondering if 1. this plugin is still being actively developed? I'd like to get the MailPoet addon, once the SSL issue is fixed, but want to be sure I'm investing in something that will be around a while.

Also 2. have you looked into the use of the words "exit intent" as well as the general concept? I'd just hate to see you get sued or something, if you're not prepared. I'm no lawyer, but it looks like "exit intent" is copyrighted by OptinMonster, and the general concept is patented by another company. They sued each other, from what I can see. Anyway, it all seems silly and like an idea that existed long before their patent/copyright. But I'm just curious as to how you see it and if it's a threat to the existence of this plugin?

**Comment by julien731** [comment]
The development of this plugin has been questioned for some time to be honest. But we decided to continue it and make some major changes.

The code has been almost completely refactored. There are still a few pieces that need to be worked on, but it's not much.

When we finished (and tested) it, we'll re-work the website, which includes renewing the SSL certificate.

Regarding the "exit intent" term, in all honesty, I didn't know it was patented. As you said, it's an idea that existed long before their patent/copyright so it sounds kinda ridiculous for someone to "patent" and enforce the use of a common expression / idea. Anyway, if they come to us threatening of a lawsuit we will definitely not go ahead and confront them.

**Comment by FiddlerStudios** [comment]
That's great to hear you're continuing development. Is there an ETA on the new version? We're kinda looking to implement MailPoet asap, and it's annoying to send those new subscriptions to 

I researched this all some, because I was hoping that the Bloom plugin from ElegantThemes would add this kind of a trigger since your plugin didn't seem to be an option (prior to your reply). Their reply was that it was patented and so they wouldn't touch it. My research revealed that the whole concept of a "exit intent" or "exit behavior" is patented by a company named Bounce Exchange: http://www.google.com/patents/US20130290117. The problem is there's plenty of preexisting uses (see here: https://www.marketingtechblog.com/bounce-exchange-exit-intent/#comment-305003) of this kind of behavior, prior to the patent. So it's a bogus patent, but I don't think it's been invalidated yet. OptinMonster trademarked the term "Exit Intent" at some point. They also sued Bounce Exchange, I think trying to invalidate the patent. However, I don't understand the legal language well enough to know if that lawsuit was settled or how it ended? Someone outside suggested that OptinMonster spent millions and the result was not favorable, but I don't really know any details of how it ended.

So what does all this mean? Well if I were you I wouldn't use the term "exit intents" or anything like it such as "exit behavior". It also means that technically, your plugin may be in violation of this patent, even if it's a bogus patent and should be invalidated. So just something to be aware of. It might also mean that yourselves, ElegantThemes, maybe OptinMonster, and a bunch of others might be able to join together or form some sort of collation and try and fight this ridiculous patent... just a side thought. It would be nice to get a "big dog" involved who could put some money and legal muscle behind this, since it's so ridiculous. I'm no lawyer, and this isn't legal counsel, I'm just sharing what I know and my opinion.

**Comment by julien731** [comment]
Indeed it looks like a bogus patent to me. It's like patenting a standard user behavior in an internet browser. Sounds bullshit to me.

Regarding the *exit intent* term, maybe we'll avoid using it.

Honestly, I don't want to start a war or anything. Bounce Exchange is way bigger than us and they would most likely crush us in case or conflict. However, unless there is an official request or any kind of thread, we won't stop doing what we do.

Regarding the ETA, the new version of the plugin is ready. We just need to get the site back on track with a new SSL certificate and an updated design that will match the new version of the plugin. I hope we can do that this week.

**Comment by FiddlerStudios** [comment]
Cool. Thanks for letting me know. I checked last night, but it was the same
site with broken SSL. If you don't mind, I'd appreciate a ping when it's
ready.


*Tevya Washburn* ↓ FiddlerStudios <http://fiddlerstudios.com> ↓ 801.891.3324

I only respond to emails once every 24hrs; learn why
<http://fiddlerstudios.com/how-to/creating-an-email-understanding/>.

**Comment by julien731** [comment]
Sure thing. I'll ping you here when it's ready.

**Comment by FiddlerStudios** [comment]
Soooo... Is there really a new version coming, or what's the status?

Tevya Washburn

801-891-3324 | tevya@fiddlerstudios.com

**Comment by FiddlerStudios** [comment]
So, is there really an updated version coming? Or did you change your minds?


*Tevya Washburn* ↓ FiddlerStudios <http://fiddlerstudios.com> ↓ 801.891.3324

I only respond to emails once every 24hrs; learn why
<http://fiddlerstudios.com/how-to/creating-an-email-understanding/>.
