### ISSUE TITLE
betteropt.in SSL has expired

### ISSUE THREAD

**Issue by AGSoftAU** [ThemeAvenue/BetterOptin#34]
As a secure connection is enforced it should really be fixed.

**Comment by AGSoftAU** [comment]
This is still an issue. Is this project dead?

**Comment by SiamKreative** [comment]
Hi there,

We're working a new version. No more free plugin with addons, it will only be a Premium Plugin.

Cheers

**Comment by AGSoftAU** [comment]
ah okay. That seems like a better idea to be honest.

**Comment by SiamKreative** [comment]
Just wanted to let you know that we finally had enough time to work on the website. Check it out https://betteropt.in/. SSL is now working again :)
