### ISSUE TITLE
Ok, I was about to direct someone over to the site....

### ISSUE THREAD

**Issue by BurlesonBrad** [ThemeAvenue/BetterOptin#44]
....and then I realized a gremlin stole your cdn :exclamation: 
![betteroptin-cdn](https://cloud.githubusercontent.com/assets/6208757/15733525/36173486-284c-11e6-8ea7-b912acd6e92c.png)

aahhhhhh poop :poop:

**Comment by siamkreative** [comment]
Thanks for reporting this. Dunno what is wrong with our CDN. Possibly something with the SSL. I turned it off for now.
