### ISSUE TITLE
If submission fails, cookie is still set

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#6]
If for any reason the submission (to WordPress, MailChimp, etc) fails, then we still set the cookie. As a result, the user can't see the modal again.

**Comment by toddadel** [comment]
Seeing the same bug. Is there any ETA on when it will be resolved? Thanks!

**Comment by SiamKreative** [comment]
Moreover, a fail that lead to an `alert()` and a redirect to `/?wpbo_submit=fail`, shows up as a conversion in the Dashboard > Analytics!

**Comment by julien731** [comment]
Failsafe method added
